debug: false

server:
  port: 8084
  servlet:
    context-path: /user

spring:
  application:
    name: user

eureka:
  instance:
    status-page-url-path: ${server.servlet.context-path}/info
    health-check-url-path: ${server.servlet.context-path}/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
